
server:
  port: 8080
#信息
info:
  contact:
    email: test
    phone: test


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
        exclude:
  security:
    enabled: false
  server:
    port: 8088

#datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dhtest?useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver